### ISSUE TITLE
Add BOM support to .csv exports for special character support

### ISSUE THREAD

**Issue by xECK29x** [archibalduk/Eastside-Hockey-Manager-Editor#19]
We often run into issues with imports/exports from the editor to csv due to a lack of support of a BOM. This is causing issues and manual cleanup when dealing with Polish, Czech, Hungarian and German cities/towns.

Example: Großburgwedel:GER is rendered as gro?burgwedel:ger in an export requiring manual find-replace work.

**Comment by archibalduk** [comment]
Added for v1.2.0
