### ISSUE TITLE
Feature Request(s): New cleanup tools for duplicate career history entries

### ISSUE THREAD

**Issue by xECK29x** [archibalduk/Eastside-Hockey-Manager-Editor#27]
1) I'd love to be able to do is mass-replace team names if I happened to link the wrong item or made a change. I love how "Find and replace competitions" works and I'd like to expand this functionality to clubs.

2) I'd also like the simplicity of being able to add 'd' to a career history template to remove items. This allows me to pull down massive amounts of career history entries and easily mass-delete them as I would staff/players.

**Comment by archibalduk** [comment]
1. Added for 1.1.8
2. This can be done by setting GP to zero in the spreadsheet (this marks the item for deletion)
