### ISSUE TITLE
Functionality Request: Error condition/Mass Cleanup of overage player rights

### ISSUE THREAD

**Issue by xECK29x** [archibalduk/Eastside-Hockey-Manager-Editor#34]
Would it be possible to do a check between max age in a league competition and flag overage/ineligible player rights and enable a mass-cleanup option? I have to do this manually by player DOB and a mass select/delete within player rights tab. Would be nice to flag any I miss or just have a mass-cleanup option.

Thanks!

**Comment by archibalduk** [comment]
Added for v1.2.0
