### ISSUE TITLE
Functionality Request: Mass-Cleanup of overage junior players

### ISSUE THREAD

**Issue by xECK29x** [archibalduk/Eastside-Hockey-Manager-Editor#36]
Similar to the player rights cleanup, mass-edit functionality for clearing overage players for junior leagues would save a lot of manual effort.

To clean up the junior leagues I have to filter all players by YOB and manually remove the player rights and set the player to UFA, I have to do this across at least 10 leagues.

**Comment by archibalduk** [comment]
Added for v1.2.0
