### ISSUE TITLE
Improvement Request: Dealing with Duplicate Career History Entires

### ISSUE THREAD

**Issue by xECK29x** [archibalduk/Eastside-Hockey-Manager-Editor#59]
I think the process works great for duplicates which involves an inactive & active club. We do need to improve the process where exact duplicate values for the same season, club, league and stats. 

1) If there is an exact match across multiple lines for the same season as described above -> delete all but one row.
2) For duplicate stat lines across the same season (say club or competition are different) -> validate against synonym file to see if club/comp should be updated and if duplicate perform cleanup as described in 1).

**Comment by xECK29x** [comment]
![image](https://github.com/archibalduk/Eastside-Hockey-Manager-Editor/assets/15521739/07cde5f7-6a5d-40a4-95b9-174f7e2c5865)

Good example to use is Lee Bonner (Hull Seahawks), see 2013 season (lines 6-7) for an example of 1) and 2014 season (lines 11-12) for an example of 2).

Test DB with Synonym file attached. 

[xECK29x-Rosters-v8-Test Copy.zip](https://github.com/archibalduk/Eastside-Hockey-Manager-Editor/files/11628573/xECK29x-Rosters-v8-Test.Copy.zip)

**Comment by archibalduk** [comment]
Added for v1.2.2
